#!/usr/bin/env bash

# Environment
RV=0
TMPDIR=$(mktemp -d -t heapusage.XXXXXX)

# Run application
./heapusage -m 1024 -f ./ex001 > ${TMPDIR}/out.txt 2> ${TMPDIR}/err.txt

# Expected
# Heapusage - https://github.com/d99kris/heapusage
# Command: ./ex001
# Process: 4803
#
# HEAP SUMMARY:
#     in use at exit: 12221 bytes in 4 blocks
#   total heap usage: 5 allocs, 1 frees, 13332 bytes allocated
#
# 6666 bytes in 3 block(s) are lost, originally allocated at:
#    at 0x00007f13ad3a5f9d: malloc + 49
#    at 0x0000564b911588e7: main + 55
#    at 0x00007f13acfe83f1: __libc_start_main + 241
#    at 0x0000564b911587aa: _start + 42
#
# 5555 bytes in 1 block(s) are lost, originally allocated at:
#    at 0x00007f13ad3a5f9d: malloc + 49
#    at 0x0000564b911588c2: main + 18
#    at 0x00007f13acfe83f1: __libc_start_main + 241
#    at 0x0000564b911587aa: _start + 42
#
# LEAK SUMMARY:
#    definitely lost: 12221 bytes in 4 blocks
#

# Check result - header
LINE=$(head -1 ${TMPDIR}/err.txt)
EXPT="Heapusage - https://github.com/d99kris/heapusage"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

LINE=$(head -5 ${TMPDIR}/err.txt | tail -1)
EXPT="HEAP SUMMARY:"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

LINE=$(head -6 ${TMPDIR}/err.txt | tail -1)
EXPT="    in use at exit: 12221 bytes in 4 blocks"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Check result - details
LINE=$(grep 'are lost' ${TMPDIR}/err.txt | head -1 | tail -1)
EXPT="6666 bytes in 3 block(s) are lost, originally allocated at:"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

LINE=$(grep 'are lost' ${TMPDIR}/err.txt | head -2 | tail -1)
EXPT="5555 bytes in 1 block(s) are lost, originally allocated at:"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Check result - summary
LINE=$(tail -3 ${TMPDIR}/err.txt | head -1)
EXPT="LEAK SUMMARY:"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

LINE=$(tail -2 ${TMPDIR}/err.txt | head -1)
EXPT="   definitely lost: 12221 bytes in 4 blocks"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Cleanup
rm -rf ${TMPDIR}

# Exit
exit ${RV}
