#!/usr/bin/env bash

# Environment
RV=0
TMPDIR=$(mktemp -d -t heapusage.XXXXXX)

# Run application
./heapusage -t all -m 0 -o ${TMPDIR}/out.txt ./ex005 > ${TMPDIR}/stdout.txt 2> ${TMPDIR}/stderr.txt

# Heapusage - https://github.com/d99kris/heapusage
# Command: ./ex005
# Process: 42668
#
# Invalid memory access at:
#    at 0x00007fb970b2100a:
#    at 0x00007fb97092e210:
#    at 0x000055badc60b1bd: main + 52
#    at 0x00007fb97090f0b3: __libc_start_main + 243
#    at 0x000055badc60b0ce: _start + 46
#  Address 0x55badc986ff8 is 0 bytes inside a block of size 8 free'd at:
#    at 0x00007fb970b178c8: free + 166
#    at 0x000055badc60b1af: main + 38
#    at 0x00007fb97090f0b3: __libc_start_main + 243
#    at 0x000055badc60b0ce: _start + 46
#  Block was alloc'd at:
#    at 0x00007fb970b177d4: malloc + 167
#    at 0x000055badc60b19f: main + 22
#    at 0x00007fb97090f0b3: __libc_start_main + 243
#    at 0x000055badc60b0ce: _start + 46
#
# HEAP SUMMARY:
#     in use at exit: 0 bytes in 0 blocks
#   total heap usage: 1 allocs, 1 frees, 8 bytes allocated
#    peak heap usage: 8 bytes allocated
#
# LEAK SUMMARY:
#    definitely lost: 0 bytes in 0 blocks
#

# Check result - header
LINE=$(head -1 ${TMPDIR}/out.txt)
EXPT="Heapusage*- https://github.com/d99kris/heapusage"
if [[ "${LINE}" != ${EXPT} ]]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Check result - details
LINE=$(head -5 ${TMPDIR}/out.txt | tail -1)
EXPT="Invalid memory access at:"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

LINE=$(printf "%d\n" $(grep 'is 0 bytes inside a block of size' ${TMPDIR}/out.txt | wc -l))
EXPT="1"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

LINE=$(printf "%d\n" $(grep 'Block was alloc' ${TMPDIR}/out.txt | wc -l))
EXPT="1"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Cleanup
rm -rf ${TMPDIR}

# Exit
exit ${RV}
