#!/usr/bin/env bash

# Environment
RV=0
TMPDIR=$(mktemp -d -t heapusage.XXXXXX)

# Run application
./heapusage -t all -m 0 -s SIGUSR1 -o ${TMPDIR}/out.txt ./ex006 > ${TMPDIR}/stdout.txt 2> ${TMPDIR}/stderr.txt &
CHILD_PID="${!}"
sleep 1
kill -s SIGUSR1 $(pidof ex006)
wait ${CHILD_PID}

# Heapusage - https://github.com/d99kris/heapusage
# Command: ./ex006
# Process: 30520
#
# ON DEMAND REPORT
# HEAP SUMMARY:
#     in use at exit: 1111 bytes in 1 blocks
#   total heap usage: 1 allocs, 0 frees, 1111 bytes allocated
#    peak heap usage: 1111 bytes allocated
#
# 1111 bytes in 1 block(s) are lost, originally allocated at:
#    at 0x0000000100bd2ba4: malloc_wrap + 164
#    at 0x0000000100767f34: main + 24
#    at 0x00000001914ea0e0: start + 2360
#
# LEAK SUMMARY:
#    definitely lost: 1111 bytes in 1 blocks
#
# HEAP SUMMARY:
#     in use at exit: 3333 bytes in 2 blocks
#   total heap usage: 2 allocs, 0 frees, 3333 bytes allocated
#    peak heap usage: 3333 bytes allocated
#
# 2222 bytes in 1 block(s) are lost, originally allocated at:
#    at 0x0000000100bd2ba4: malloc_wrap + 164
#    at 0x0000000100767f48: main + 44
#    at 0x00000001914ea0e0: start + 2360
#
# 1111 bytes in 1 block(s) are lost, originally allocated at:
#    at 0x0000000100bd2ba4: malloc_wrap + 164
#    at 0x0000000100767f34: main + 24
#    at 0x00000001914ea0e0: start + 2360
#
# LEAK SUMMARY:
#    definitely lost: 3333 bytes in 2 blocks
#

# Check presence of on demand header
LINE=$(head -5 ${TMPDIR}/out.txt | tail -1)
EXPT="ON DEMAND REPORT"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Check first peak heap usage
LINE=$(grep 'peak heap usage' ${TMPDIR}/out.txt | head -1 | tail -1)
EXPT="   peak heap usage: 1111 bytes allocated"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Check second peak heap usage
LINE=$(grep 'peak heap usage' ${TMPDIR}/out.txt | head -2 | tail -1)
EXPT="   peak heap usage: 3333 bytes allocated"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Cleanup
rm -rf ${TMPDIR}

# Exit
exit ${RV}
