#!/usr/bin/env bash

# Environment
RV=0
TMPDIR=$(mktemp -d -t heapusage.XXXXXX)

# Run application
./heapusage -t leak -m 0 -o ${TMPDIR}/out.txt ./ex003 > ${TMPDIR}/stdout.txt 2> ${TMPDIR}/stderr.txt

# Expected out.txt:
# Heapusage - https://github.com/d99kris/heapusage
# Command: ./ex003
# Process: 16158
#
# HEAP SUMMARY:
#     in use at exit: 24 bytes in 1 blocks
#   total heap usage: 7 allocs, 6 frees, 106 bytes allocated
#    peak heap usage: 94 bytes allocated
#
# 24 bytes in 1 block(s) are lost, originally allocated at:
#    at 0x0000000102fa9d5b: malloc_wrap + 43
#    at 0x00007fff202f8daa: operator new(unsigned long) + 26
#    at 0x0000000102f95f3e: main + 414
#    at 0x00007fff2034d631: start + 1
#    at 0x0000000000000001:
#
# LEAK SUMMARY:
#    definitely lost: 24 bytes in 1 blocks
#

# Check result - header
LINE=$(head -1 ${TMPDIR}/out.txt)
EXPT="Heapusage - https://github.com/d99kris/heapusage"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Check result - leak summary
LINE=$(grep "definitely lost" ${TMPDIR}/out.txt | awk -F' in ' '{print $2}')
EXPT="1 blocks"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Cleanup
rm -rf ${TMPDIR}

# Exit
exit ${RV}
