#!/usr/bin/env bash

# Environment
RV=0
TMPDIR=$(mktemp -d)

# Run application
./heapusage -t all -m 0 -o ${TMPDIR}/out.txt ./ex005 > ${TMPDIR}/stdout.txt 2> ${TMPDIR}/stderr.txt

# ==42668== Heapusage - https://github.com/d99kris/heapusage
# ==42668== 
# ==42668== Invalid memory access at:
# ==42668==    at 0x00007fb970b2100a: 
# ==42668==    at 0x00007fb97092e210: 
# ==42668==    at 0x000055badc60b1bd: main + 52
# ==42668==    at 0x00007fb97090f0b3: __libc_start_main + 243
# ==42668==    at 0x000055badc60b0ce: _start + 46
# ==42668==  Address 0x55badc986ff8 is 0 bytes inside a block of size 8 free'd at:
# ==42668==    at 0x00007fb970b178c8: free + 166
# ==42668==    at 0x000055badc60b1af: main + 38
# ==42668==    at 0x00007fb97090f0b3: __libc_start_main + 243
# ==42668==    at 0x000055badc60b0ce: _start + 46
# ==42668==  Block was alloc'd at:
# ==42668==    at 0x00007fb970b177d4: malloc + 167
# ==42668==    at 0x000055badc60b19f: main + 22
# ==42668==    at 0x00007fb97090f0b3: __libc_start_main + 243
# ==42668==    at 0x000055badc60b0ce: _start + 46
# ==42668== 
# ==42668== HEAP SUMMARY:
# ==42668==     in use at exit: 0 bytes in 0 blocks
# ==42668==   total heap usage: 1 allocs, 1 frees, 8 bytes allocated
# ==42668==    peak heap usage: 8 bytes allocated
# ==42668== 
# ==42668== LEAK SUMMARY:
# ==42668==    definitely lost: 0 bytes in 0 blocks
# ==42668== 

# Check result - header
LINE=$(cat ${TMPDIR}/out.txt | cut -d'=' -f5 | head -1 | tail -1)
EXPT=" Heapusage - https://github.com/d99kris/heapusage"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Check result - details
LINE=$(cat ${TMPDIR}/out.txt | cut -d'=' -f5 | head -3 | tail -1)
EXPT=" Invalid memory access at:"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

LINE=$(printf "%d\n" $(grep 'is 0 bytes inside a block of size' ${TMPDIR}/out.txt | wc -l))
EXPT="1"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

LINE=$(printf "%d\n" $(grep 'Block was alloc' ${TMPDIR}/out.txt | wc -l))
EXPT="1"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Cleanup
rm -rf ${TMPDIR}

# Exit
exit ${RV}

