#!/usr/bin/env bash

# Environment
RV=0
TMPDIR=$(mktemp -d -t heapusage.XXXXXX)

# Run application
./heapusage -t all -m 0 -o ${TMPDIR}/out.txt ./ex004 > ${TMPDIR}/stdout.txt 2> ${TMPDIR}/stderr.txt

# Heapusage - https://github.com/d99kris/heapusage
# Command: ./ex004
# Process: 41495
#
# Invalid memory access at:
#    at 0x00007f9be67d200a:
#    at 0x00007f9be65df210:
#    at 0x00005581ca3f7194: main + 43
#    at 0x00007f9be65c00b3: __libc_start_main + 243
#    at 0x00005581ca3f70ae: _start + 46
#  Address 0x5581cadbb000 is 0 bytes after a block of size 8 alloc'd at:
#    at 0x00007f9be67c87d4: malloc + 167
#    at 0x00005581ca3f717f: main + 22
#    at 0x00007f9be65c00b3: __libc_start_main + 243
#    at 0x00005581ca3f70ae: _start + 46
#
# HEAP SUMMARY:
#     in use at exit: 8 bytes in 1 blocks
#   total heap usage: 1 allocs, 0 frees, 8 bytes allocated
#    peak heap usage: 8 bytes allocated
#
# 8 bytes in 1 block(s) are lost, originally allocated at:
#    at 0x00007f9be67c87d4: malloc + 167
#    at 0x00005581ca3f717f: main + 22
#    at 0x00007f9be65c00b3: __libc_start_main + 243
#    at 0x00005581ca3f70ae: _start + 46
#
# LEAK SUMMARY:
#    definitely lost: 8 bytes in 1 blocks
#

# Check result - header
LINE=$(head -1 ${TMPDIR}/out.txt)
EXPT="Heapusage - https://github.com/d99kris/heapusage"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Check result - details
LINE=$(head -5 ${TMPDIR}/out.txt | tail -1)
EXPT="Invalid memory access at:"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

LINE=$(printf "%d\n" $(grep 'is 0 bytes after a block of size' ${TMPDIR}/out.txt | wc -l))
EXPT="1"
if [ "${LINE}" != "${EXPT}" ]; then
  echo "Output mismatch: \"${LINE}\" != \"${EXPT}\""
  RV=1
fi

# Cleanup
rm -rf ${TMPDIR}

# Exit
exit ${RV}
